name: Daily LINE Fitness Bot

on:
  schedule:
    # 07:30 Asia/Taipei == 23:30 UTC (前一天)
    - cron: "30 23 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # 讓日期時區一致（我們的程式也有指定 Asia/Taipei，但設這個較保險）
      TZ: Asia/Taipei
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Run bot
        run: node index.mjs
